// src/lib/utils/roaster-logo-plate.ts
import { roasterImagePresets } from "@/lib/imagekit";

/**
 * The plate a roaster logo sits on, tinted for contrast against the logo itself.
 *
 * Inverse contrast per theme: a white/light logo gets a dark plate in light mode
 * and the neutral plate in dark mode; a dark/coloured logo gets the neutral plate
 * in light mode and a light plate in dark mode.
 *
 * Both plates are vignettes — light centre, darker rim — so the logo always sits
 * on the brighter part of its plate. The hardcoded oklch pairs are the opposite
 * theme's --background/--card, written out because a plate has to keep its tint
 * when the theme it belongs to is not the active one.
 *
 * Both results are written out as complete literal class strings. Tailwind scans
 * source text, so a class assembled at runtime (`dark:${bg}`) is only ever
 * generated by luck — because some other file happens to contain the same literal.
 *
 * Every colour stop goes through a var(). Tailwind emits no rule at all for an
 * arbitrary value holding a nested colour function — `bg-[radial-gradient(...,
 * oklch(0.24_0.014_59.46)_0%,...)]` produced nothing, which is why the light-mode
 * dark plate and the dark-mode light plate used to render with no gradient.
 */
const LIGHT_LOGO_PLATE =
  "bg-[radial-gradient(circle_at_center,var(--plate-on-light-center)_0%,var(--plate-on-light-edge)_100%)] dark:bg-[radial-gradient(circle_at_center,var(--muted)_0%,var(--background)_100%)]";

const DARK_LOGO_PLATE =
  "bg-[radial-gradient(circle_at_center,var(--background)_0%,var(--muted)_100%)] dark:bg-[radial-gradient(circle_at_center,var(--plate-on-dark-center)_0%,var(--plate-on-dark-edge)_100%)]";

/** ImageKit URL for a roaster's logo, or null when there is no slug. */
export function roasterLogoUrl(slug: string | null | undefined): string | null {
  return slug ? roasterImagePresets.roasterLogo(`roasters/${slug}-logo`) : null;
}

/**
 * Plate classes for a logo of known luminance.
 *
 * `logoIsLight` comes from roasters.logo_is_light, sampled once at ingest (see
 * scripts/backfill-roaster-logo-luminance.ts). This used to be a canvas read on
 * every card mount. NULL — never sampled — falls back to the neutral plate,
 * matching what the old hook rendered before its sample landed.
 */
export function roasterPlateClass(
  logoIsLight: boolean | null | undefined
): string {
  return logoIsLight ? LIGHT_LOGO_PLATE : DARK_LOGO_PLATE;
}
