// src/hooks/useRoasterLogoPlate.ts
"use client";

import { useMemo } from "react";
import { roasterImagePresets } from "@/lib/imagekit";
import { useImageColor } from "@/hooks/useImageColor";

/**
 * The plate a roaster logo sits on, tinted for contrast against the logo itself.
 *
 * Inverse contrast per theme: a white/light logo gets a dark plate in light mode
 * and the neutral plate in dark mode; a dark/coloured logo gets the neutral plate
 * in light mode and a light plate in dark mode.
 *
 * Both results are written out as complete literal class strings. Tailwind scans
 * source text, so a class assembled at runtime (`dark:${bg}`) is only ever
 * generated by luck — because some other file happens to contain the same literal.
 */
const LIGHT_LOGO_PLATE =
  "bg-[radial-gradient(circle_at_center,oklch(0.24_0.014_59.46)_0%,oklch(0.195_0.01_59.58)_100%)] dark:bg-[radial-gradient(circle_at_center,var(--muted)_0%,var(--background)_100%)]";

const DARK_LOGO_PLATE =
  "bg-[radial-gradient(circle_at_center,var(--muted)_0%,var(--background)_100%)] dark:bg-[radial-gradient(circle_at_center,oklch(0.965_0.015_79.92)_0%,oklch(0.982_0.009_79.92)_100%)]";

type RoasterLogoPlate = {
  /** ImageKit URL for the roaster's logo, or null when there is no slug. */
  logoUrl: string | null;
  /** Tailwind classes for the plate behind the logo. */
  plateClass: string;
};

/**
 * Derives a roaster's logo URL from its slug and the contrast-matched plate
 * classes from the logo's own colour. Samples the image on a canvas, so callers
 * are client components; before the sample lands, `plateClass` is the neutral
 * plate — no flash of the wrong tint.
 */
export function useRoasterLogoPlate(
  slug: string | null | undefined
): RoasterLogoPlate {
  const logoUrl = useMemo(
    () =>
      slug ? roasterImagePresets.roasterLogo(`roasters/${slug}-logo`) : null,
    [slug]
  );

  // isDark === true means the *logo* is light/white, so it needs a dark plate.
  const { isDark } = useImageColor(logoUrl);

  return {
    logoUrl,
    plateClass: isDark ? LIGHT_LOGO_PLATE : DARK_LOGO_PLATE,
  };
}
