/**
 * Curated gear catalog, seeded by scripts/seed-gear-catalog.ts.
 *
 * Rollout is one brew method at a time (docs/gear-directory-plan.md). Price rule: nothing
 * over ₹1,00,000, and every product needs a reason beyond "a roaster stocks it".
 *
 * Aliases feed scripts/gear-match.ts: every word of an alias must appear in a store
 * listing, most words wins. Keep each alias as short as it can be while staying
 * unambiguous, and don't alias a product by a word its siblings share (no bare "v60").
 *
 * experience_levels is editorial ("who we'd point this at"), multi-level by default.
 */

import type { GearCategory } from "../src/lib/validations/gear";

export type GearSeed = {
  slug: string;
  name: string;
  brand: string;
  model: string;
  category: GearCategory;
  subcategory: string;
  brew_methods: string[];
  experience_levels: ("beginner" | "enthusiast" | "expert")[];
  aliases: string[];
};

const FILTER_METHODS = [
  "v60",
  "kalita",
  "chemex",
  "aeropress",
  "french-press",
  "cold-brew",
];
const ALL_METHODS = [
  ...FILTER_METHODS,
  "moka-pot",
  "filter-coffee",
  "espresso",
];
const POUR_OVER = ["v60", "kalita", "chemex"];

/** Wave 1: AeroPress + pour-over (V60, Kalita, Chemex) and the kit they share. */
export const GEAR_SEED: GearSeed[] = [
  // ── AeroPress ──────────────────────────────────────────────────────────────
  {
    slug: "aeropress-original",
    name: "AeroPress Original",
    brand: "AeroPress",
    model: "Original",
    category: "brewer",
    subcategory: "immersion-press",
    brew_methods: ["aeropress"],
    experience_levels: ["beginner", "enthusiast", "expert"],
    aliases: ["aeropress", "aeropress original"],
  },
  {
    slug: "aeropress-go",
    name: "AeroPress Go",
    brand: "AeroPress",
    model: "Go",
    category: "brewer",
    subcategory: "immersion-press",
    brew_methods: ["aeropress"],
    experience_levels: ["beginner", "enthusiast"],
    aliases: ["aeropress go"],
  },
  {
    slug: "aeropress-go-plus",
    name: "AeroPress Go Plus",
    brand: "AeroPress",
    model: "Go Plus",
    category: "brewer",
    subcategory: "immersion-press",
    brew_methods: ["aeropress"],
    experience_levels: ["beginner", "enthusiast"],
    aliases: ["aeropress go plus"],
  },
  {
    slug: "aeropress-clear",
    name: "AeroPress Clear",
    brand: "AeroPress",
    model: "Clear",
    category: "brewer",
    subcategory: "immersion-press",
    brew_methods: ["aeropress"],
    experience_levels: ["beginner", "enthusiast", "expert"],
    aliases: ["aeropress clear"],
  },
  {
    slug: "aeropress-xl",
    name: "AeroPress XL",
    brand: "AeroPress",
    model: "XL",
    category: "brewer",
    subcategory: "immersion-press",
    brew_methods: ["aeropress"],
    experience_levels: ["enthusiast", "expert"],
    aliases: ["aeropress xl"],
  },
  {
    slug: "aeropress-premium",
    name: "AeroPress Premium",
    brand: "AeroPress",
    model: "Premium",
    category: "brewer",
    subcategory: "immersion-press",
    brew_methods: ["aeropress"],
    experience_levels: ["enthusiast", "expert"],
    aliases: ["aeropress premium"],
  },
  {
    slug: "aeropress-paper-filters",
    name: "AeroPress Paper Filters (350)",
    brand: "AeroPress",
    model: "Paper Filters",
    category: "filter",
    subcategory: "paper-filter",
    brew_methods: ["aeropress"],
    experience_levels: ["beginner", "enthusiast", "expert"],
    aliases: [
      "aeropress filter",
      "aeropress filter paper",
      "aeropress paper filter",
    ],
  },
  {
    slug: "aeropress-metal-filter",
    name: "AeroPress Stainless Steel Filter",
    brand: "AeroPress",
    model: "Stainless Steel Filter",
    category: "filter",
    subcategory: "metal-filter",
    brew_methods: ["aeropress"],
    experience_levels: ["enthusiast", "expert"],
    aliases: ["aeropress metal filter", "aeropress stainless steel filter"],
  },

  // ── Pour-over drippers ─────────────────────────────────────────────────────
  {
    slug: "hario-v60-plastic-dripper",
    name: "Hario V60 Plastic Dripper",
    brand: "Hario",
    model: "V60 Plastic",
    category: "brewer",
    subcategory: "dripper",
    brew_methods: ["v60"],
    experience_levels: ["beginner", "enthusiast"],
    aliases: ["v60 plastic", "v60 polypropylene"],
  },
  {
    slug: "hario-v60-ceramic-dripper",
    name: "Hario V60 Ceramic Dripper",
    brand: "Hario",
    model: "V60 Ceramic",
    category: "brewer",
    subcategory: "dripper",
    brew_methods: ["v60"],
    experience_levels: ["beginner", "enthusiast", "expert"],
    aliases: ["v60 ceramic"],
  },
  {
    slug: "hario-v60-glass-dripper",
    name: "Hario V60 Glass Dripper",
    brand: "Hario",
    model: "V60 Glass",
    category: "brewer",
    subcategory: "dripper",
    brew_methods: ["v60"],
    experience_levels: ["enthusiast", "expert"],
    aliases: ["v60 glass dripper"],
  },
  {
    slug: "hario-v60-neo-dripper",
    name: "Hario V60 Neo Dripper",
    brand: "Hario",
    model: "V60 Neo",
    category: "brewer",
    subcategory: "dripper",
    brew_methods: ["v60"],
    experience_levels: ["beginner", "enthusiast"],
    aliases: ["v60 neo", "hario neo"],
  },
  {
    slug: "hario-switch",
    name: "Hario Switch Immersion Dripper",
    brand: "Hario",
    model: "Switch",
    category: "brewer",
    subcategory: "dripper",
    brew_methods: ["v60"],
    experience_levels: ["beginner", "enthusiast", "expert"],
    aliases: ["hario switch"],
  },
  {
    slug: "kalita-wave-155",
    name: "Kalita Wave 155 Dripper",
    brand: "Kalita",
    model: "Wave 155",
    category: "brewer",
    subcategory: "dripper",
    brew_methods: ["kalita"],
    experience_levels: ["beginner", "enthusiast"],
    aliases: ["kalita wave 155", "kalita 155 dripper"],
  },
  {
    slug: "kalita-wave-185",
    name: "Kalita Wave 185 Dripper",
    brand: "Kalita",
    model: "Wave 185",
    category: "brewer",
    subcategory: "dripper",
    brew_methods: ["kalita"],
    experience_levels: ["beginner", "enthusiast", "expert"],
    aliases: ["kalita wave 185", "kalita 185 dripper"],
  },
  {
    slug: "chemex-classic-6-cup",
    name: "Chemex Classic 6-Cup",
    brand: "Chemex",
    model: "Classic 6-Cup",
    category: "brewer",
    subcategory: "pour-over-carafe",
    brew_methods: ["chemex"],
    experience_levels: ["beginner", "enthusiast", "expert"],
    aliases: ["chemex six cup", "chemex 6 cup", "chemex classic six"],
  },
  {
    slug: "chemex-classic-3-cup",
    name: "Chemex Classic 3-Cup",
    brand: "Chemex",
    model: "Classic 3-Cup",
    category: "brewer",
    subcategory: "pour-over-carafe",
    brew_methods: ["chemex"],
    experience_levels: ["beginner", "enthusiast"],
    aliases: ["chemex three cup", "chemex 3 cup", "chemex classic three"],
  },
  {
    slug: "chemex-glass-handle-6-cup",
    name: "Chemex Glass Handle 6-Cup",
    brand: "Chemex",
    model: "Glass Handle 6-Cup",
    category: "brewer",
    subcategory: "pour-over-carafe",
    brew_methods: ["chemex"],
    experience_levels: ["enthusiast", "expert"],
    aliases: ["chemex glass handle six", "chemex glass handle 6"],
  },
  {
    slug: "chemex-glass-handle-3-cup",
    name: "Chemex Glass Handle 3-Cup",
    brand: "Chemex",
    model: "Glass Handle 3-Cup",
    category: "brewer",
    subcategory: "pour-over-carafe",
    brew_methods: ["chemex"],
    experience_levels: ["enthusiast", "expert"],
    aliases: ["chemex glass handle three", "chemex glass handle 3"],
  },
  {
    slug: "origami-dripper-s",
    name: "Origami Dripper S",
    brand: "Origami",
    model: "Dripper S",
    category: "brewer",
    subcategory: "dripper",
    brew_methods: ["v60", "kalita"],
    experience_levels: ["enthusiast", "expert"],
    aliases: ["origami dripper small"],
  },
  {
    slug: "origami-dripper-m",
    name: "Origami Dripper M",
    brand: "Origami",
    model: "Dripper M",
    category: "brewer",
    subcategory: "dripper",
    brew_methods: ["v60", "kalita"],
    experience_levels: ["enthusiast", "expert"],
    aliases: ["origami dripper medium"],
  },
  {
    slug: "origami-air-s",
    name: "Origami Air Dripper S",
    brand: "Origami",
    model: "Air S",
    category: "brewer",
    subcategory: "dripper",
    brew_methods: ["v60", "kalita"],
    experience_levels: ["beginner", "enthusiast"],
    aliases: ["origami air small", "origami dripper air small"],
  },
  {
    slug: "origami-air-m",
    name: "Origami Air Dripper M",
    brand: "Origami",
    model: "Air M",
    category: "brewer",
    subcategory: "dripper",
    brew_methods: ["v60", "kalita"],
    experience_levels: ["beginner", "enthusiast"],
    aliases: ["origami air medium", "origami dripper air medium"],
  },
  {
    slug: "timemore-crystal-eye-dripper",
    name: "Timemore Crystal Eye Dripper",
    brand: "Timemore",
    model: "Crystal Eye",
    category: "brewer",
    subcategory: "dripper",
    brew_methods: ["v60"],
    experience_levels: ["beginner", "enthusiast"],
    aliases: ["crystal eye dripper"],
  },
  {
    slug: "timemore-b75-dripper",
    name: "Timemore B75 Dripper",
    brand: "Timemore",
    model: "B75",
    category: "brewer",
    subcategory: "dripper",
    brew_methods: ["v60"],
    experience_levels: ["enthusiast", "expert"],
    aliases: ["timemore b75 dripper"],
  },
  {
    slug: "cafec-flower-dripper-deep-27",
    name: "Cafec Flower Dripper Deep 27",
    brand: "Cafec",
    model: "Flower Dripper Deep 27",
    category: "brewer",
    subcategory: "dripper",
    brew_methods: ["v60"],
    experience_levels: ["enthusiast", "expert"],
    aliases: ["cafec flower dripper"],
  },

  // ── Filters & servers ──────────────────────────────────────────────────────
  {
    slug: "hario-v60-paper-filters",
    name: "Hario V60 Paper Filters (100)",
    brand: "Hario",
    model: "V60 Paper Filters",
    category: "filter",
    subcategory: "paper-filter",
    brew_methods: ["v60"],
    experience_levels: ["beginner", "enthusiast", "expert"],
    aliases: [
      "hario v60 filter",
      "hario v60 paper",
      "hario filter paper",
      "hario dripper filter",
    ],
  },
  {
    slug: "kalita-wave-filters",
    name: "Kalita Wave Filters (100)",
    brand: "Kalita",
    model: "Wave Filters",
    category: "filter",
    subcategory: "paper-filter",
    brew_methods: ["kalita"],
    experience_levels: ["beginner", "enthusiast", "expert"],
    aliases: ["kalita filter"],
  },
  {
    slug: "chemex-bonded-filters",
    name: "Chemex Bonded Filters",
    brand: "Chemex",
    model: "Bonded Filters",
    category: "filter",
    subcategory: "paper-filter",
    brew_methods: ["chemex"],
    experience_levels: ["beginner", "enthusiast", "expert"],
    aliases: ["chemex filter", "chemex bonded"],
  },
  {
    slug: "origami-paper-filters",
    name: "Origami Cone Paper Filters (100)",
    brand: "Origami",
    model: "Cone Paper Filters",
    category: "filter",
    subcategory: "paper-filter",
    brew_methods: ["v60"],
    experience_levels: ["enthusiast", "expert"],
    aliases: ["origami filter", "origami paper filter"],
  },
  {
    slug: "cafec-abaca-filters",
    name: "Cafec Abaca Paper Filters",
    brand: "Cafec",
    model: "Abaca",
    category: "filter",
    subcategory: "paper-filter",
    brew_methods: ["v60"],
    experience_levels: ["enthusiast", "expert"],
    aliases: ["cafec abaca"],
  },
  {
    slug: "cafec-light-roast-filters",
    name: "Cafec Light Roast Paper Filters",
    brand: "Cafec",
    model: "Light Roast Filters",
    category: "filter",
    subcategory: "paper-filter",
    brew_methods: ["v60"],
    experience_levels: ["enthusiast", "expert"],
    aliases: ["cafec light roast"],
  },
  {
    slug: "cafec-medium-dark-roast-filters",
    name: "Cafec Medium-Dark Roast Paper Filters",
    brand: "Cafec",
    model: "Medium-Dark Roast Filters",
    category: "filter",
    subcategory: "paper-filter",
    brew_methods: ["v60"],
    experience_levels: ["enthusiast", "expert"],
    aliases: ["cafec medium dark roast"],
  },
  {
    slug: "cafec-dark-roast-filters",
    name: "Cafec Dark Roast Paper Filters",
    brand: "Cafec",
    model: "Dark Roast Filters",
    category: "filter",
    subcategory: "paper-filter",
    brew_methods: ["v60"],
    experience_levels: ["enthusiast", "expert"],
    aliases: ["cafec dark roast"],
  },
  {
    slug: "timemore-paper-filters",
    name: "Timemore Cone Paper Filters (100)",
    brand: "Timemore",
    model: "Cone Paper Filters",
    category: "filter",
    subcategory: "paper-filter",
    brew_methods: ["v60"],
    experience_levels: ["beginner", "enthusiast", "expert"],
    aliases: ["timemore paper filter", "timemore filter paper"],
  },
  {
    slug: "timemore-b75-filters",
    name: "Timemore B75 Paper Filters",
    brand: "Timemore",
    model: "B75 Paper Filters",
    category: "filter",
    subcategory: "paper-filter",
    brew_methods: ["v60"],
    experience_levels: ["enthusiast", "expert"],
    aliases: ["timemore b75 filter", "timemore b75 filter paper"],
  },
  {
    slug: "hario-v60-glass-server",
    name: "Hario V60 Glass Server",
    brand: "Hario",
    model: "V60 Range Server",
    category: "accessory",
    subcategory: "server",
    brew_methods: POUR_OVER,
    experience_levels: ["beginner", "enthusiast", "expert"],
    aliases: ["v60 glass server", "hario coffee server", "v60 range server"],
  },
  {
    slug: "hario-v60-drip-decanter",
    name: "Hario V60 Drip Decanter",
    brand: "Hario",
    model: "V60 Drip Decanter",
    category: "brewer",
    subcategory: "dripper",
    brew_methods: ["v60"],
    experience_levels: ["beginner", "enthusiast"],
    aliases: ["v60 drip decanter"],
  },

  // ── Kettles ────────────────────────────────────────────────────────────────
  {
    slug: "hario-buono-kettle",
    name: "Hario Buono Kettle",
    brand: "Hario",
    model: "Buono",
    category: "kettle",
    subcategory: "gooseneck-kettle",
    brew_methods: POUR_OVER,
    experience_levels: ["beginner", "enthusiast"],
    aliases: ["hario buono", "buono kettle"],
  },
  {
    slug: "fellow-stagg-ekg",
    name: "Fellow Stagg EKG Electric Kettle",
    brand: "Fellow",
    model: "Stagg EKG",
    category: "kettle",
    subcategory: "electric-gooseneck-kettle",
    brew_methods: [...POUR_OVER, "aeropress"],
    experience_levels: ["enthusiast", "expert"],
    aliases: ["stagg ekg"],
  },
  {
    slug: "fellow-stagg-ekg-pro",
    name: "Fellow Stagg EKG Pro Electric Kettle",
    brand: "Fellow",
    model: "Stagg EKG Pro",
    category: "kettle",
    subcategory: "electric-gooseneck-kettle",
    brew_methods: [...POUR_OVER, "aeropress"],
    experience_levels: ["expert"],
    aliases: ["stagg ekg pro"],
  },
  {
    slug: "timemore-fish-smart-kettle",
    name: "Timemore Fish Smart Electric Kettle",
    brand: "Timemore",
    model: "Fish Smart",
    category: "kettle",
    subcategory: "electric-gooseneck-kettle",
    brew_methods: [...POUR_OVER, "aeropress"],
    experience_levels: ["enthusiast", "expert"],
    aliases: ["timemore fish smart"],
  },
  {
    slug: "timemore-fish-smart-pro-kettle",
    name: "Timemore Fish Smart Pro Electric Kettle",
    brand: "Timemore",
    model: "Fish Smart Pro",
    category: "kettle",
    subcategory: "electric-gooseneck-kettle",
    brew_methods: [...POUR_OVER, "aeropress"],
    experience_levels: ["enthusiast", "expert"],
    aliases: ["timemore fish smart pro", "timemore fish pro"],
  },
  {
    slug: "brewista-artisan-kettle",
    name: "Brewista Artisan Gooseneck Kettle",
    brand: "Brewista",
    model: "Artisan",
    category: "kettle",
    subcategory: "electric-gooseneck-kettle",
    brew_methods: [...POUR_OVER, "aeropress"],
    experience_levels: ["enthusiast", "expert"],
    aliases: ["brewista artisan"],
  },

  // ── Scales ─────────────────────────────────────────────────────────────────
  {
    slug: "hario-v60-drip-scale",
    name: "Hario V60 Drip Scale",
    brand: "Hario",
    model: "V60 Drip Scale",
    category: "scale",
    subcategory: "brew-scale",
    brew_methods: [...POUR_OVER, "aeropress"],
    experience_levels: ["beginner", "enthusiast"],
    aliases: ["hario drip scale", "v60 drip scale"],
  },
  {
    slug: "timemore-black-mirror-basic-2",
    name: "Timemore Black Mirror Basic 2.0",
    brand: "Timemore",
    model: "Black Mirror Basic 2.0",
    category: "scale",
    subcategory: "brew-scale",
    brew_methods: [...POUR_OVER, "aeropress", "espresso"],
    experience_levels: ["beginner", "enthusiast", "expert"],
    aliases: ["timemore basic 2", "black mirror basic 2"],
  },
  {
    slug: "timemore-black-mirror-basic-3",
    name: "Timemore Black Mirror Basic 3.0",
    brand: "Timemore",
    model: "Black Mirror Basic 3.0",
    category: "scale",
    subcategory: "brew-scale",
    brew_methods: [...POUR_OVER, "aeropress", "espresso"],
    experience_levels: ["beginner", "enthusiast", "expert"],
    aliases: ["timemore basic 3", "black mirror basic 3"],
  },

  // ── Hand grinders ──────────────────────────────────────────────────────────
  {
    slug: "hario-mini-mill-slim",
    name: "Hario Mini Mill Slim",
    brand: "Hario",
    model: "Mini Mill Slim",
    category: "grinder",
    subcategory: "hand-grinder",
    brew_methods: ["french-press", "aeropress", "v60", "cold-brew"],
    experience_levels: ["beginner"],
    aliases: ["hario mini slim", "hario mini mill"],
  },
  {
    slug: "hario-skerton-pro",
    name: "Hario Skerton Pro",
    brand: "Hario",
    model: "Skerton Pro",
    category: "grinder",
    subcategory: "hand-grinder",
    brew_methods: ["french-press", "aeropress", "v60", "cold-brew"],
    experience_levels: ["beginner"],
    aliases: ["hario skerton"],
  },
  {
    slug: "timemore-chestnut-c2",
    name: "Timemore Chestnut C2",
    brand: "Timemore",
    model: "Chestnut C2",
    category: "grinder",
    subcategory: "hand-grinder",
    brew_methods: [...FILTER_METHODS, "moka-pot"],
    experience_levels: ["beginner", "enthusiast"],
    aliases: ["timemore c2", "chestnut c2"],
  },
  {
    slug: "timemore-chestnut-c3",
    name: "Timemore Chestnut C3",
    brand: "Timemore",
    model: "Chestnut C3",
    category: "grinder",
    subcategory: "hand-grinder",
    brew_methods: [...FILTER_METHODS, "moka-pot"],
    experience_levels: ["beginner", "enthusiast"],
    aliases: ["timemore c3", "chestnut c3"],
  },
  {
    slug: "timemore-chestnut-c3s",
    name: "Timemore Chestnut C3S",
    brand: "Timemore",
    model: "Chestnut C3S",
    category: "grinder",
    subcategory: "hand-grinder",
    brew_methods: [...FILTER_METHODS, "moka-pot"],
    experience_levels: ["beginner", "enthusiast"],
    aliases: ["timemore c3s", "chestnut c3s"],
  },
  {
    slug: "timemore-chestnut-c3-esp-pro",
    name: "Timemore Chestnut C3 ESP Pro",
    brand: "Timemore",
    model: "Chestnut C3 ESP Pro",
    category: "grinder",
    subcategory: "hand-grinder",
    brew_methods: ALL_METHODS,
    experience_levels: ["enthusiast"],
    aliases: ["timemore c3 esp"],
  },
  {
    slug: "1zpresso-q-air",
    name: "1Zpresso Q Air",
    brand: "1Zpresso",
    model: "Q Air",
    category: "grinder",
    subcategory: "hand-grinder",
    brew_methods: FILTER_METHODS,
    experience_levels: ["beginner", "enthusiast"],
    aliases: ["1zpresso q air"],
  },
  {
    slug: "1zpresso-jx-pro",
    name: "1Zpresso JX-Pro",
    brand: "1Zpresso",
    model: "JX-Pro",
    category: "grinder",
    subcategory: "hand-grinder",
    brew_methods: ALL_METHODS,
    experience_levels: ["enthusiast", "expert"],
    aliases: ["1zpresso jx pro"],
  },
  {
    slug: "1zpresso-j-ultra",
    name: "1Zpresso J-Ultra",
    brand: "1Zpresso",
    model: "J-Ultra",
    category: "grinder",
    subcategory: "hand-grinder",
    brew_methods: ["espresso", "aeropress", "moka-pot"],
    experience_levels: ["expert"],
    aliases: ["1zpresso j ultra"],
  },
  {
    slug: "1zpresso-k-ultra",
    name: "1Zpresso K-Ultra",
    brand: "1Zpresso",
    model: "K-Ultra",
    category: "grinder",
    subcategory: "hand-grinder",
    brew_methods: ALL_METHODS,
    experience_levels: ["enthusiast", "expert"],
    aliases: ["1zpresso k ultra"],
  },
  {
    slug: "1zpresso-x-ultra",
    name: "1Zpresso X-Ultra",
    brand: "1Zpresso",
    model: "X-Ultra",
    category: "grinder",
    subcategory: "hand-grinder",
    brew_methods: ALL_METHODS,
    experience_levels: ["enthusiast", "expert"],
    aliases: ["1zpresso x ultra"],
  },
  {
    slug: "kingrinder-k6",
    name: "Kingrinder K6",
    brand: "Kingrinder",
    model: "K6",
    category: "grinder",
    subcategory: "hand-grinder",
    brew_methods: ALL_METHODS,
    experience_levels: ["beginner", "enthusiast"],
    aliases: ["kingrinder k6"],
  },
  {
    slug: "kingrinder-p2",
    name: "Kingrinder P2",
    brand: "Kingrinder",
    model: "P2",
    category: "grinder",
    subcategory: "hand-grinder",
    brew_methods: ["v60", "aeropress", "french-press", "cold-brew"],
    experience_levels: ["beginner"],
    aliases: ["kingrinder p2"],
  },
  {
    slug: "comandante-c40-mk4",
    name: "Comandante C40 MK4",
    brand: "Comandante",
    model: "C40 MK4",
    category: "grinder",
    subcategory: "hand-grinder",
    brew_methods: ALL_METHODS,
    experience_levels: ["enthusiast", "expert"],
    aliases: ["comandante c40 mk4"],
  },
];

/**
 * Existing user-entered gear_catalog rows that are really one of the seeded products.
 * Keyed by the dirty row's name (citext unique). The seed script turns the first one into
 * the canonical row in place (keeping its id, so user_gear links survive) and repoints
 * user_gear from the rest before deleting them.
 *
 * Not folded (ambiguous or not in this wave): "v60" (material unknown), "Mokapot",
 * "Dedica E685", "French Press" (Sipologie).
 */
export const GEAR_FOLDS: Record<string, string> = {
  "Q Air": "1zpresso-q-air",
  "": "aeropress-original",
  Aeropress: "aeropress-original",
  "Kingrinder K6": "kingrinder-k6",
  "Manual Grinders": "timemore-chestnut-c3s",
  "C3 Esp": "timemore-chestnut-c3-esp-pro",
  "hario neo": "hario-v60-neo-dripper",
  "Hario Switch": "hario-switch",
  D27: "cafec-flower-dripper-deep-27",
};
