// src/components/common/Icon.tsx
import type { IconProps } from "@phosphor-icons/react";
// Explicit icon registry — only the icons actually used in the app.
//
// IMPORTANT: do NOT switch back to `import * as PhosphorIcons` with dynamic
// `PhosphorIcons[name]` access. That namespace + dynamic-key pattern defeats
// tree-shaking and bundles all ~1,500 Phosphor icons (~17MB of source) into the
// client. Add new icons to ICONS below; `IconName` then enforces them at compile
// time, so `npm run type-check` flags any usage of an unregistered name.
import {
  ArrowBendUpLeft,
  ArrowClockwise,
  ArrowCounterClockwise,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowsLeftRight,
  ArrowSquareOut,
  ArrowUp,
  ArrowUpRight,
  Bell,
  BookmarkSimple,
  BookOpen,
  Brain,
  Calculator,
  Calendar,
  Camera,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  CaretUpDown,
  ChartBar,
  ChatCircle,
  Check,
  CheckCircle,
  Checks,
  Circle,
  CircleHalf,
  CircleNotch,
  CirclesFour,
  ClockClockwise,
  ClockCounterClockwise,
  CloudRain,
  CloudSun,
  Code,
  Coffee,
  CoffeeBean,
  Compass,
  Cookie,
  Copy,
  CurrencyCircleDollar,
  CurrencyInr,
  Database,
  DiscordLogo,
  Dot,
  DotsNine,
  DotsThree,
  Drop,
  Envelope,
  EnvelopeSimple,
  Eye,
  FacebookLogo,
  Fire,
  Flask,
  Funnel,
  Gear,
  GearSix,
  GenderFemale,
  GenderIntersex,
  GenderMale,
  Ghost,
  Globe,
  GraduationCap,
  Graph,
  Handshake,
  Heart,
  Hourglass,
  Image,
  Info,
  InstagramLogo,
  Leaf,
  Lightbulb,
  Lightning,
  Link,
  List,
  ListBullets,
  ListChecks,
  ListNumbers,
  LockKey,
  MagicWand,
  MagnifyingGlass,
  MapPin,
  MapTrifold,
  Megaphone,
  Moon,
  Mountains,
  Notebook,
  Package,
  Palette,
  Path,
  Pause,
  PencilSimple,
  Plant,
  Play,
  Plus,
  PlusCircle,
  Printer,
  Quotes,
  RedditLogo,
  RocketLaunch,
  Ruler,
  Scales,
  Share,
  ShareNetwork,
  Shield,
  ShoppingCart,
  SidebarSimple,
  SignOut,
  Sliders,
  SlidersHorizontal,
  Sparkle,
  SpeakerHigh,
  SpeakerSlash,
  Spinner,
  Square,
  SquaresFour,
  Stack,
  Star,
  StarHalf,
  Storefront,
  Sun,
  Tag,
  Target,
  TelegramLogo,
  Thermometer,
  ThermometerSimple,
  ThumbsDown,
  ThumbsUp,
  Timer,
  Trash,
  TrashSimple,
  Tree,
  TrendUp,
  Trophy,
  TwitterLogo,
  Upload,
  User,
  UserCircle,
  UserPlus,
  Users,
  UsersThree,
  Vibrate,
  Warning,
  WarningCircle,
  WhatsappLogo,
  Wrench,
  X,
  XCircle,
  XLogo,
} from "@phosphor-icons/react/dist/ssr";
import type {
  ComponentPropsWithoutRef,
  ComponentType,
  CSSProperties,
} from "react";

const ICONS = {
  ArrowBendUpLeft,
  ArrowClockwise,
  ArrowCounterClockwise,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowsLeftRight,
  ArrowSquareOut,
  ArrowUp,
  ArrowUpRight,
  Bell,
  BookmarkSimple,
  BookOpen,
  Brain,
  Calculator,
  Calendar,
  Camera,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  CaretUpDown,
  ChartBar,
  ChatCircle,
  Check,
  CheckCircle,
  Checks,
  Circle,
  CircleHalf,
  CircleNotch,
  CirclesFour,
  ClockClockwise,
  ClockCounterClockwise,
  CloudRain,
  CloudSun,
  Code,
  Coffee,
  CoffeeBean,
  Compass,
  Cookie,
  Copy,
  CurrencyCircleDollar,
  CurrencyInr,
  Database,
  DiscordLogo,
  Dot,
  DotsNine,
  DotsThree,
  Drop,
  Envelope,
  EnvelopeSimple,
  Eye,
  FacebookLogo,
  Fire,
  Flask,
  Funnel,
  Gear,
  GearSix,
  GenderFemale,
  GenderIntersex,
  GenderMale,
  Ghost,
  Globe,
  GraduationCap,
  Graph,
  Handshake,
  Heart,
  Hourglass,
  Image,
  Info,
  InstagramLogo,
  Leaf,
  Lightbulb,
  Lightning,
  Link,
  List,
  ListBullets,
  ListChecks,
  ListNumbers,
  LockKey,
  MagicWand,
  MagnifyingGlass,
  MapPin,
  MapTrifold,
  Megaphone,
  Moon,
  Mountains,
  Notebook,
  Package,
  Palette,
  Path,
  Pause,
  PencilSimple,
  Plant,
  Play,
  Plus,
  PlusCircle,
  Printer,
  Quotes,
  RedditLogo,
  RocketLaunch,
  Ruler,
  Scales,
  Share,
  ShareNetwork,
  Shield,
  ShoppingCart,
  SidebarSimple,
  SignOut,
  Sliders,
  SlidersHorizontal,
  Sparkle,
  SpeakerHigh,
  SpeakerSlash,
  Spinner,
  Square,
  SquaresFour,
  Stack,
  Star,
  StarHalf,
  Storefront,
  Sun,
  Tag,
  Target,
  TelegramLogo,
  Thermometer,
  ThermometerSimple,
  ThumbsDown,
  ThumbsUp,
  Timer,
  Trash,
  TrashSimple,
  Tree,
  TrendUp,
  Trophy,
  TwitterLogo,
  Upload,
  User,
  UserCircle,
  UserPlus,
  Users,
  UsersThree,
  Vibrate,
  Warning,
  WarningCircle,
  WhatsappLogo,
  Wrench,
  X,
  XCircle,
  XLogo,
} satisfies Record<string, ComponentType<IconProps>>;

export type IconName = keyof typeof ICONS;

type IconColor =
  | "primary"
  | "muted"
  | "accent"
  | "destructive"
  | "glass"
  | "white";

type CustomIconProps = {
  name: IconName;
  size?: IconProps["size"];
  className?: string;
  color?: IconColor;
  /** Phosphor weight. Defaults to `duotone`. Use `fill` for solid icons (e.g. wishlist). */
  weight?: IconProps["weight"];
} & Omit<
  ComponentPropsWithoutRef<"svg">,
  "className" | "size" | "color" | "weight"
>;

export const Icon = ({
  name,
  size = 20,
  className = "inline-block",
  color = "primary",
  weight = "duotone",
  style,
  ...props
}: CustomIconProps) => {
  const IconComponent = ICONS[name];

  if (!IconComponent) {
    console.error(
      `Icon "${name}" not found in the registry. Add it to ICONS in Icon.tsx.`
    );
    return <span>❌</span>; // Fallback
  }

  // Map color prop → Phosphor `color` (sets SVG `fill`). Phosphor does not read
  // --ph-* vars; duotone secondary is the same fill at 0.2 opacity.
  const colorMap: Record<IconColor, string> = {
    primary: "var(--primary)",
    muted: "var(--muted-foreground)",
    accent: "var(--accent)",
    destructive: "var(--destructive)",
    glass: "var(--foreground)",
    white: "#fff",
  };

  const fill = colorMap[color ?? "primary"];

  return (
    <IconComponent
      className={className}
      size={size}
      color={fill}
      weight={weight}
      style={
        {
          "--ph-primary": fill,
          "--ph-secondary": fill,
          ...style,
        } as CSSProperties
      }
      {...props}
    />
  );
};
